### ISSUE TITLE
Checklist for version 0.3.0

### ISSUE THREAD

**Issue by AaronKutch** [Robbepop/apint#46]
Here are the PRs that will need to be done before the crate is in a state that could be released.
 - [ ] Reorganize the entire crate's structure (#29)
 - [ ] Rustfmt PR
 - [ ] Use `MaybeUninit` and `NonZeroUsize` PR (#39)
 - [ ] Fix big and little endian problems (#25, #20, fix the `from_vec_u64` TODOs, and some serialization things)
 - [ ] Better constructors (#44) (I will not do the generic binary operation stuff, only constructor stuff)
 - [ ] Error PR where I fix a bunch of related TODOs
 - [ ] Fix all of the TODOs besides performance related TODOs
 - [ ] Do any `contributions.md` stuff we want
 - [ ] Release 0.3.0

**Comment by AaronKutch** [comment]
I updated the checklist with everything I could think of. I have a week left before university starts again.

**Comment by Robbepop** [comment]
Thank you very much for this nice list!
Many important points!
However, I am a bit unsure if the time plannings of one week are a bit optimistic. ^^

**Comment by AaronKutch** [comment]
I'll stay as co-author for now, and maybe reconsider after 0.3.0. Would it be possible for you to review a PR every week, only skipping a week occasionally whenever work is too hard or something? In the past there was periods of months between reviews, but I estimate that there will be ~20 PRs in between now and where I want 0.3.0 to be.

**Comment by Robbepop** [comment]
It mostly depends on the reviewability of the incoming PRs. If a PR is easy to review I will mostly do it right away. If it takes several hours on the other hand I am taking more time to start the review.

**Comment by AaronKutch** [comment]
This semester is by far the hardest semester I have ever had. I have had to work on weekends and even during this spring break to keep the school work from running me over. I think I am feeling some burn out right now. I still want to get one more PR in before end of semester stuff kicks in.

**Comment by AaronKutch** [comment]
Issue #42 is fixed now, lets keep that issue up a little longer in case we encounter a problem. I will do a PR for issue #41 to have `BitWidth` construction use `TryFrom` and other stuff. Then, I will have a PR to extract a new `fuzz.rs` using improved `BitWidth` ergonomics, testing, and feature flags. Then, you can get your GitHub Actions PR working.
